# Generated by Django 3.0.8 on 2020-08-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeclareFlowParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_application_code', models.CharField(max_length=50)),
                ('flow_agent', models.CharField(max_length=50)),
                ('dir_path', models.FilePathField(allow_files=False, allow_folders=True)),
                ('file_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KeyModel',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RunOracleActionParams',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('log_file', models.CharField(max_length=300)),
                ('sql_file', models.CharField(max_length=300)),
                ('label', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RunScriptParams',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('script_directory', models.CharField(max_length=300)),
                ('content_to_launch', models.CharField(max_length=300)),
                ('label', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateStateIdParams',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('process_date', models.DateField()),
                ('process_status', models.CharField(max_length=300, null=True)),
                ('label', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CleanFlowParams',
            fields=[
                ('keymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='params.KeyModel')),
                ('flow_application_code', models.CharField(max_length=50)),
            ],
            bases=('params.keymodel',),
        ),
        migrations.CreateModel(
            name='ExtractTableParams',
            fields=[
                ('keymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='params.KeyModel')),
                ('spool_file', models.CharField(max_length=300)),
                ('log_file', models.CharField(max_length=300)),
                ('sql_file', models.CharField(max_length=300)),
                ('table_ref', models.CharField(max_length=50)),
            ],
            bases=('params.keymodel',),
        ),
        migrations.CreateModel(
            name='LoadTableParams',
            fields=[
                ('keymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='params.KeyModel')),
                ('data_file', models.CharField(max_length=300)),
                ('log_file', models.CharField(max_length=300)),
                ('ctl_file', models.CharField(max_length=300)),
            ],
            bases=('params.keymodel',),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('service', models.CharField(max_length=200)),
                ('instance', models.CharField(max_length=10, null=True)),
                ('tags', models.ManyToManyField(to='params.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='keymodel',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.TestCase'),
        ),
        migrations.CreateModel(
            name='CheckFlowParams',
            fields=[
                ('keymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='params.KeyModel')),
                ('flow_application_code', models.CharField(max_length=50)),
                ('status_to_check', models.CharField(choices=[('20', '20'), ('23', '23'), ('30', '30')], max_length=2)),
                ('expected_files', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.Server')),
            ],
            bases=('params.keymodel',),
        ),
    ]
