# Generated by Django 3.0.8 on 2020-08-05 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareParams',
            fields=[
                ('keymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='params.KeyModel')),
                ('expected', models.CharField(max_length=300)),
                ('outgoing', models.CharField(max_length=300)),
            ],
            bases=('params.keymodel',),
        ),
    ]
